### ISSUE TITLE
Need to revise ValidationErrors

### ISSUE THREAD

**Issue by Envek** [evilmartians/evil-client#22]
The problematic place is: https://github.com/evilmartians/evil-client/commit/f4e28584ee406becc7cf6d36a89a75aec2070230#diff-a76cfc1380d763d073577d9d3d19ef3bR64

Here we throw out any original exception and make it `ValidationError` even if it is apparently not a such.

I have faced it several times while contributing to [ebay_api](https://github.com/nepalez/ebay_api) or even bugs in the evil-client itself (e.g., with I18n error fixed in https://github.com/evilmartians/evil-client/commit/89e3a8b968797569880d3e7ea37c2725eb6c80f8) and it was always a pain to find the root cause of the problem.

So we need to distinguish usual exceptions (bugs) from real validation errors somehow. Have no idea how to do it at the moment though.

**Comment by nepalez** [comment]
Yeah, you're right. I've dropped this resque along with `ValidationError`. This stuff really not needed (it was a sort of premature optimization).
