### ISSUE TITLE
Bypassing ssl verification with HTTPClient

### ISSUE THREAD

**Issue by dem23step** [evilmartians/evil-client#26]
Hi guys! First of all, it's awesome client! 

During development I stucked with self-signed certificate problem.
Can't figure out how to use `connection` writer with Faraday or HTTPClient, for example.

Supposing to use HTTPClient: 

```ruby
client = HTTPClient.new
client.ssl_config.verify_mode = OpenSSL::SSL::VERIFY_NONE
```

But I can't figure out how to use it with Evil::Client descendant 🤷 

Any thoughts?

**Comment by Envek** [comment]
You need to write your own connection handler with customized client (by default builtin `Net::HTTP` is being used):
```ruby
class MyConnection
  class << self
    def call(env)
      request = Rack::Request.new(env)
      uri     = URI request.url
      body    = Array(request.body)
      method  = request.env["REQUEST_METHOD"].upcase
      headers = request.env["HTTP_Variables"]
      
      result = client.request(method, uri, body: request.body, header: headers)
      [result.code, result.headers, Array(result.body)]
    end

    private

    def client
      @client ||= HTTPClient.new.tap do |client|
        client.ssl_config.verify_mode = OpenSSL::SSL::VERIFY_NONE # Don't do that in production!
      end
    end
  end
end
```

And then use it instead of default [`Evil::Client::Connection`](https://github.com/evilmartians/evil-client/blob/8c5af01b645f1d658dc184a819dc8fbf0471dd0d/lib/evil/client/connection.rb):
```ruby
class MyAPI < Evil::Client
  path { "https://localhost/" }
  
  connection { MyConnection }

  operation :get do
    http_method :get
    path { "/" }
  end

  response(200, 201) { |_, _, (data, *)| data }
end

puts MyAPI.new.get.inspect
```

---

**WARNING**: DO NOT disable SSL verification in production! Either use Let's Encrypt or (if not possible) add your self-signed certificate to trusted certificates in your app production server or docker image.

**Comment by dem23step** [comment]
@Envek huge thanks!  🎉 🎉 🎉 

I almost got it on my own, but your version is much cleaner, no doubt 😃 

There's possible bug I encountered while navigating gem's codebase:
In my particular case I'm using custom authentication middleware, so my code (using your version) looks like smth:

```ruby
class Connection
  # your code from above
end

class Authentication
  def initialize(app)
    puts app.inspect # Evil::Client::Connection (should be Connection provided in Client below)
    @app = app
  end

  def call(env)
    authenticate(env)
    @app.call(env) # fails with self-signed certificate error as expected
  end

  private
  
    def authenticate(env)
      # some non-trivial authentication:
      # 1) request third-party server with basic auth
      # 2) get Bearer token from response header
      # 3) place it in env['HTTP_Variables']
    end
end

class Client < Evil::Client
  ...
  connection { Connection }
  middleware Authentication
  ...
end
```

It doesn't use my custom `Connection` for some reason, but AFAICS on [lib/evil/client/container/operation.rb:15](https://github.com/evilmartians/evil-client/blob/8c5af01b645f1d658dc184a819dc8fbf0471dd0d/lib/evil/client/container/operation.rb#L15) it shoulda use connection provided by me

Unfortunately, I can't debug it right now, maybe you can check and provide any solution?

I ended up with this:

```ruby
class Authentication
  def initialize(app)
    @app = Connection # explicit usage of custom connection
  end
  ...
end
```

P.S. I'm using v 3.0.4 of gem

**Comment by Envek** [comment]
Use assignment for connections:
```ruby
class MyAPI < Evil::Client  
  self.connection = MyConnection
end
```

Actually `connection { MyConnection }` just doesn't work at all, sorry. See [the code](https://github.com/evilmartians/evil-client/blob/8c5af01b645f1d658dc184a819dc8fbf0471dd0d/lib/evil/client.rb#L57-L65) and [the docs](https://github.com/evilmartians/evil-client/blob/8c5af01b645f1d658dc184a819dc8fbf0471dd0d/docs/helpers/connection.md).

**Comment by dem23step** [comment]
Solved! 🎉 

Thanks 👍
